[build]
  command = "npm install tsx cli fastify @fastify/cors @prisma/client prisma mongodb mongoose mongoclient && npx prisma generate && npm run build"
  publish = "src"

[start]
  command = "npm start"